import logo from './logo.png'
import loadinglogo from './loadinglogo.png'
import tutorial from './tutorial.png'
import nf2 from './2NF.png'
import nf3 from './3NF.png'
import bcnf from './BCNF.png'
import selectsql from './SelectExample.png'
import andsql from './AndExample.png'
import orsql from './OrExample.png'
import wheresql from './WhereExample.png'
import orderbysql from './OrderbyExample.png'
import notsql from './NotExample.png'
import groupbysql from './GroupbyExample.png'
import havingsql from './HavingExample.png'
import distinctsql from './DistinctExample.png'
import fdtestpic from './FDTestPic.png'
import keyspracticepic from './KeysPracticePic.png'
import keystestpic from './KeyTestPic.png'
import normalisationpracticepic from './NormalisationPracticePic.png'
import normalisationtestpic from './NormalisationTestPic.png'
import sqlpracticepic from './SQLPracticePic.png'
import maxminsql from './MaxMinExample.png'
import countsql from './CountExample.png'
import sumsql from './SumExample.png'
import avgsql from './AverageExample.png'
import star3 from './star3.png'
import star2 from './star2.png'
import sqltest1pic from './SQLTest1Pic.png'
import joinsqlpractice from './JoinsSQLPractice.png'
import innerjoinexample from './InnerJoinExample.png'
import joinsgif from './Joins.gif'
import leftjoinexample from './LeftJoinExample.png'
import rightjoinexample from './RightJoinExample.png'
import fullouterexample from './FullOuterJoinExample.png'
import independentnestedexample from './IndependendNestedExample.png'
import dependentnestedexample from './DependentNestedExample.png'
import allexample from './AllExample.png'
import anyexample from './AnyExample.png'
import notinexample from './NotinExample.png'
import inexample from './InExample.png'
import existsexample from './ExistsExample.png'
import notexistsexample from './NotExistsExample.png'
import sqltest2pic from './SQLTest2Pic.png'
import hintlens from './HintLens.png'
import progresspic from './Progress.png'
import finalsqltestpic from './FinalSQLTestPic.png'
import yay from './Yay.gif'
import normalisationmurderpic from './NormalisationMurderPic.png'
import sqlmurderpic from './SQLMurderPic.png'
import normalisationvandalismpic from './NormalisationVandalismPic.png'
import sqlvandalismpic from './SQLVandalismPic.png'
import normalisationkidnap from './NormalisationKidnapPic.png'
import sqlkidnappic from './SQLKidnapPic.png'
import easy from './Easy.png'
import medium from './Medium.png'
import difficult from './Difficult.png'

export {
    logo, loadinglogo, tutorial, nf2, nf3, bcnf, selectsql, andsql, orsql, wheresql,
    orderbysql, distinctsql, notsql, groupbysql, havingsql, keystestpic, normalisationtestpic,
    normalisationpracticepic, sqlpracticepic, fdtestpic, keyspracticepic, avgsql, sumsql,
    maxminsql, countsql, star2, star3, sqltest1pic, joinsqlpractice, innerjoinexample,
    joinsgif, fullouterexample, leftjoinexample, rightjoinexample, inexample, allexample,
    dependentnestedexample, anyexample, existsexample, notinexample, notexistsexample,
    independentnestedexample, sqltest2pic, hintlens, progresspic, finalsqltestpic, yay, sqlkidnappic, sqlmurderpic,
    normalisationkidnap, sqlvandalismpic, normalisationmurderpic, normalisationvandalismpic, easy, medium, difficult
}